version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "ORIKAMIxNEP"
    labels:
      - "help wanted"
