name: "CD"
description: "CD"

inputs:
  branch-name:
    description: 'Branch name'
    required: true

runs:
  using: composite
  steps:
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.USERNAME }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        script: |
          cd /var/www/procon34-cyber-wars-backend/ ${{ inputs.branch-name }} /
          git pull origin ${{ inputs.branch-name }} 
          ./gradlew clean build
