name: CD
description: CD

inputs:
  host:
    description: Host
    required: true
  username:
    description: Username
    required: true
  password:
    description: Password
    required: true
  proxy_host:
    description: Proxy host
    required: true
  proxy_password:
    description: Proxy password
    required: true
  branch-name:
    description: Branch name
    required: true

runs:
  using: composite
  steps:
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        proxy_host: ${{ inputs.proxy_host }}
        proxy_username: ${{ inputs.username }}
        proxy_password: ${{ inputs.proxy_password }}
        script: |
          cd /var/www/procon34-cyber-wars-backend/ ${{ inputs.branch-name }} /
          git pull origin ${{ inputs.branch-name }} 
          ./gradlew clean build
