name: CI
description: CI

runs:
  using: composite
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: microsoft

    - name: Setup Gradle
      uses: gradle/gradle-build-action@main

    - name: checkstyle Main
      run: ./gradlew checkstyleMain
      shell: bash

    - name: spotless Check
      run: ./gradlew spotlessCheck
      shell: bash

    - name: Build
      run: ./gradlew clean build
      shell: bash
