name: auto-assign

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    if: ${{ github.actor != "dependabot[bot]" }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: actions/github-script@main
        if: github.event_name == "pull_request"
        with:
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ${{ github.actor }}
            });
