name: Common CI

on:
  pull_request:
    branches:
      - '**'
      - '!main'
      - '!develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/gradle-build-action@main

      - name: spotless Check
        run: ./gradlew spotlessCheck
