name: develop CD
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  develop-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CD
        uses: ./.github/actions/cd
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          branch-name: develop
