name: develop CD
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  develop-cd:
    runs-on: ubuntu-latest
    steps:
      - name: CD
        uses: ./.github/actions/cd
        with:
          branch-name: develop
