name: develop CD
on:
  push:
    branches:
      - develop
jobs:
  develop-cd:
    runs-on: ubuntu-latest
    steps:
      - name: develop CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          script: |
            cd /var/www/procon34-cyber-wars-backend/develop/
            git pull origin develop
            ./gradlew clean build
