name: main CD
on:
  push:
    branches:
      - main
jobs:
  main-cd:
    runs-on: ubuntu-latest
    steps:
      - name: main CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          script: |
            cd /var/www/procon34-cyber-wars-backend/main/
            git pull origin main
            ./gradlew clean build
